name: Cancel Workflow Test

on:
  push:

concurrency:
  group: deploy-${{ github.ref}}-prod
  cancel-in-progress: true

jobs:
  staging:
    name: Deploy Staging
    runs-on: ubuntu-slim
    environment: staging
    steps:
      - name: Echo Staging
        run: |
          set -e
          echo "Staging"

  precheck:
    runs-on: ubuntu-slim
    needs: staging
    steps:
      - uses: fkirc/skip-duplicate-actions@v5
        with:
          cancel_others: true


  production:
    name: Deploy Production
    runs-on: ubuntu-slim
    environment: production
    needs: precheck
    steps:
      - name: Echo Production
        run: |
          set -e
          echo "Production"

  cancelled:
    name: Cancelled
    runs-on: ubuntu-slim
    if: ${{ cancelled() }}
    steps:
      - name: Cancelled
        run: |
          set -e
          echo "Workflow cancelled"
