name: Cancel Workflow Test

on:
  push:

concurrency:
  group: deploy-${{ github.ref}}-prod
  cancel-in-progress: true

jobs:
  staging:
    name: Deploy Staging
    runs-on: ubuntu-slim
    environment: staging
    steps:
      - name: Echo Staging
        run: |
          set -e
          echo "Staging"

  production:
    name: Deploy Production
    runs-on: ubuntu-slim
    environment: production
    needs: staging
    steps:
      - name: Only if cancelled
        if: ${{ cancelled() }}
        run: |
          set -e
          echo "This was cancelled"
      - name: Echo Production
        run: |
          set -e
          echo "Production"

  runFialure:
    name: Run on failure
    runs-on: ubuntu-slim
    needs: production
    if: ${{ failure() }}
    steps:
      - name: run on failure
        if: ${{ cancelled() }}
        run: |
          set -e
          echo "Run on failure"

